# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalcDesigne.ui'
#
# Created: Mon Feb  2 02:19:08 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_OutFlagCalc(object):
    def setupUi(self, OutFlagCalc):
        OutFlagCalc.setObjectName("OutFlagCalc")
        OutFlagCalc.resize(702, 841)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OutFlagCalc.sizePolicy().hasHeightForWidth())
        OutFlagCalc.setSizePolicy(sizePolicy)
        OutFlagCalc.setToolTip("")
        self.verticalLayoutWidget = QtGui.QWidget(OutFlagCalc)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 281, 645))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.of1Layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.of1Layout.setContentsMargins(0, 0, 0, 0)
        self.of1Layout.setObjectName("of1Layout")
        self.of1_00 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_00.setMouseTracking(False)
        self.of1_00.setToolTip("")
        self.of1_00.setCheckable(True)
        self.of1_00.setProperty("bit", 0)
        self.of1_00.setObjectName("of1_00")
        self.of1Layout.addWidget(self.of1_00)
        self.of1_01 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_01.setProperty("bit", 1)
        self.of1_01.setObjectName("of1_01")
        self.of1Layout.addWidget(self.of1_01)
        self.of1_02 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_02.setProperty("bit", 2)
        self.of1_02.setObjectName("of1_02")
        self.of1Layout.addWidget(self.of1_02)
        self.of1_03 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_03.setEnabled(False)
        self.of1_03.setCheckable(True)
        self.of1_03.setChecked(False)
        self.of1_03.setProperty("bit", 3)
        self.of1_03.setObjectName("of1_03")
        self.of1Layout.addWidget(self.of1_03)
        self.of1_04 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_04.setProperty("bit", 4)
        self.of1_04.setObjectName("of1_04")
        self.of1Layout.addWidget(self.of1_04)
        self.of1_05 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_05.setProperty("bit", 5)
        self.of1_05.setObjectName("of1_05")
        self.of1Layout.addWidget(self.of1_05)
        self.of1_06 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_06.setProperty("bit", 6)
        self.of1_06.setObjectName("of1_06")
        self.of1Layout.addWidget(self.of1_06)
        self.of1_07 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_07.setProperty("bit", 7)
        self.of1_07.setObjectName("of1_07")
        self.of1Layout.addWidget(self.of1_07)
        self.of1_08 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_08.setProperty("bit", 8)
        self.of1_08.setObjectName("of1_08")
        self.of1Layout.addWidget(self.of1_08)
        self.of1_09 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_09.setProperty("bit", 9)
        self.of1_09.setObjectName("of1_09")
        self.of1Layout.addWidget(self.of1_09)
        self.of1_10 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_10.setProperty("bit", 10)
        self.of1_10.setObjectName("of1_10")
        self.of1Layout.addWidget(self.of1_10)
        self.of1_11 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_11.setProperty("bit", 11)
        self.of1_11.setObjectName("of1_11")
        self.of1Layout.addWidget(self.of1_11)
        self.of1_12 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_12.setProperty("bit", 12)
        self.of1_12.setObjectName("of1_12")
        self.of1Layout.addWidget(self.of1_12)
        self.of1_13 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_13.setProperty("bit", 13)
        self.of1_13.setObjectName("of1_13")
        self.of1Layout.addWidget(self.of1_13)
        self.of1_14 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_14.setEnabled(False)
        self.of1_14.setProperty("bit", 14)
        self.of1_14.setObjectName("of1_14")
        self.of1Layout.addWidget(self.of1_14)
        self.of1_15 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_15.setProperty("bit", 15)
        self.of1_15.setObjectName("of1_15")
        self.of1Layout.addWidget(self.of1_15)
        self.of1_16 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_16.setEnabled(False)
        self.of1_16.setProperty("bit", 16)
        self.of1_16.setObjectName("of1_16")
        self.of1Layout.addWidget(self.of1_16)
        self.of1_17 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_17.setProperty("bit", 17)
        self.of1_17.setObjectName("of1_17")
        self.of1Layout.addWidget(self.of1_17)
        self.of1_18 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_18.setProperty("bit", 18)
        self.of1_18.setObjectName("of1_18")
        self.of1Layout.addWidget(self.of1_18)
        self.of1_19 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_19.setProperty("bit", 19)
        self.of1_19.setObjectName("of1_19")
        self.of1Layout.addWidget(self.of1_19)
        self.of1_20 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_20.setProperty("bit", 20)
        self.of1_20.setObjectName("of1_20")
        self.of1Layout.addWidget(self.of1_20)
        self.of1_21 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_21.setProperty("bit", 21)
        self.of1_21.setObjectName("of1_21")
        self.of1Layout.addWidget(self.of1_21)
        self.of1_22 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_22.setProperty("bit", 22)
        self.of1_22.setObjectName("of1_22")
        self.of1Layout.addWidget(self.of1_22)
        self.of1_23 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_23.setProperty("bit", 23)
        self.of1_23.setObjectName("of1_23")
        self.of1Layout.addWidget(self.of1_23)
        self.of1_24 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_24.setProperty("bit", 24)
        self.of1_24.setObjectName("of1_24")
        self.of1Layout.addWidget(self.of1_24)
        self.of1_25 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_25.setProperty("bit", 25)
        self.of1_25.setObjectName("of1_25")
        self.of1Layout.addWidget(self.of1_25)
        self.of1_26 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_26.setProperty("bit", 26)
        self.of1_26.setObjectName("of1_26")
        self.of1Layout.addWidget(self.of1_26)
        self.of1_27 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_27.setProperty("bit", 27)
        self.of1_27.setObjectName("of1_27")
        self.of1Layout.addWidget(self.of1_27)
        self.of1_28 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_28.setProperty("bit", 28)
        self.of1_28.setObjectName("of1_28")
        self.of1Layout.addWidget(self.of1_28)
        self.of1_29 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_29.setProperty("bit", 29)
        self.of1_29.setObjectName("of1_29")
        self.of1Layout.addWidget(self.of1_29)
        self.of1_30 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_30.setProperty("bit", 30)
        self.of1_30.setObjectName("of1_30")
        self.of1Layout.addWidget(self.of1_30)
        self.of1_31 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.of1_31.setProperty("bit", 31)
        self.of1_31.setObjectName("of1_31")
        self.of1Layout.addWidget(self.of1_31)
        self.verticalLayoutWidget_2 = QtGui.QWidget(OutFlagCalc)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 40, 392, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.of2Layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.of2Layout.setContentsMargins(0, 0, 0, 0)
        self.of2Layout.setObjectName("of2Layout")
        self.of2_00 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_00.setProperty("bit", 0)
        self.of2_00.setObjectName("of2_00")
        self.of2Layout.addWidget(self.of2_00)
        self.of2_01 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_01.setProperty("bit", 1)
        self.of2_01.setObjectName("of2_01")
        self.of2Layout.addWidget(self.of2_01)
        self.of2_02 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_02.setProperty("bit", 2)
        self.of2_02.setObjectName("of2_02")
        self.of2Layout.addWidget(self.of2_02)
        self.of2_03 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_03.setProperty("bit", 3)
        self.of2_03.setObjectName("of2_03")
        self.of2Layout.addWidget(self.of2_03)
        self.of2_04 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_04.setProperty("bit", 4)
        self.of2_04.setObjectName("of2_04")
        self.of2Layout.addWidget(self.of2_04)
        self.of2_05 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_05.setProperty("bit", 5)
        self.of2_05.setObjectName("of2_05")
        self.of2Layout.addWidget(self.of2_05)
        self.of2_06 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_06.setProperty("bit", 6)
        self.of2_06.setObjectName("of2_06")
        self.of2Layout.addWidget(self.of2_06)
        self.of2_07 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_07.setProperty("bit", 7)
        self.of2_07.setObjectName("of2_07")
        self.of2Layout.addWidget(self.of2_07)
        self.of2_08 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_08.setProperty("bit", 8)
        self.of2_08.setObjectName("of2_08")
        self.of2Layout.addWidget(self.of2_08)
        self.of2_09 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_09.setProperty("bit", 9)
        self.of2_09.setObjectName("of2_09")
        self.of2Layout.addWidget(self.of2_09)
        self.of2_10 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_10.setEnabled(False)
        self.of2_10.setProperty("bit", 10)
        self.of2_10.setObjectName("of2_10")
        self.of2Layout.addWidget(self.of2_10)
        self.of2_11 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_11.setProperty("bit", 11)
        self.of2_11.setObjectName("of2_11")
        self.of2Layout.addWidget(self.of2_11)
        self.of2_12 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_12.setProperty("bit", 12)
        self.of2_12.setObjectName("of2_12")
        self.of2Layout.addWidget(self.of2_12)
        self.of2_13 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_13.setProperty("bit", 13)
        self.of2_13.setObjectName("of2_13")
        self.of2Layout.addWidget(self.of2_13)
        self.of2_14 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_14.setProperty("bit", 14)
        self.of2_14.setObjectName("of2_14")
        self.of2Layout.addWidget(self.of2_14)
        self.of2_15 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_15.setEnabled(False)
        self.of2_15.setProperty("bit", 15)
        self.of2_15.setObjectName("of2_15")
        self.of2Layout.addWidget(self.of2_15)
        self.of2_16 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_16.setProperty("bit", 16)
        self.of2_16.setObjectName("of2_16")
        self.of2Layout.addWidget(self.of2_16)
        self.of2_17 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_17.setProperty("bit", 17)
        self.of2_17.setObjectName("of2_17")
        self.of2Layout.addWidget(self.of2_17)
        self.of2_18 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_18.setProperty("bit", 18)
        self.of2_18.setObjectName("of2_18")
        self.of2Layout.addWidget(self.of2_18)
        self.of2_19 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.of2_19.setProperty("bit", 19)
        self.of2_19.setObjectName("of2_19")
        self.of2Layout.addWidget(self.of2_19)
        self.PF_OutFlags = QtGui.QLabel(OutFlagCalc)
        self.PF_OutFlags.setGeometry(QtCore.QRect(10, 20, 281, 20))
        self.PF_OutFlags.setObjectName("PF_OutFlags")
        self.PF_OutFlags2 = QtGui.QLabel(OutFlagCalc)
        self.PF_OutFlags2.setGeometry(QtCore.QRect(300, 20, 281, 20))
        self.PF_OutFlags2.setObjectName("PF_OutFlags2")
        self.PF_OutFlags_value = QtGui.QLabel(OutFlagCalc)
        self.PF_OutFlags_value.setGeometry(QtCore.QRect(490, 730, 191, 20))
        self.PF_OutFlags_value.setObjectName("PF_OutFlags_value")
        self.PF_OutFlags2_value = QtGui.QLabel(OutFlagCalc)
        self.PF_OutFlags2_value.setGeometry(QtCore.QRect(490, 780, 191, 20))
        self.PF_OutFlags2_value.setObjectName("PF_OutFlags2_value")
        self.PF_GlobalCmd = QtGui.QLabel(OutFlagCalc)
        self.PF_GlobalCmd.setGeometry(QtCore.QRect(10, 710, 161, 20))
        self.PF_GlobalCmd.setObjectName("PF_GlobalCmd")
        self.of1_result = QtGui.QLineEdit(OutFlagCalc)
        self.of1_result.setGeometry(QtCore.QRect(490, 750, 181, 21))
        self.of1_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.of1_result.setObjectName("of1_result")
        self.of2_result = QtGui.QLineEdit(OutFlagCalc)
        self.of2_result.setGeometry(QtCore.QRect(490, 800, 181, 21))
        self.of2_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.of2_result.setObjectName("of2_result")
        self.PF_GlobalCmd_code = QtGui.QTextEdit(OutFlagCalc)
        self.PF_GlobalCmd_code.setGeometry(QtCore.QRect(10, 730, 461, 91))
        self.PF_GlobalCmd_code.setObjectName("PF_GlobalCmd_code")

        self.retranslateUi(OutFlagCalc)
        QtCore.QObject.connect(self.of1_01, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_02, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_03, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_04, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_05, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_06, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_07, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_08, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_09, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_10, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_11, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_12, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_13, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_14, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_15, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_16, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_17, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_18, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_19, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_20, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_21, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_22, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_23, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_24, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_25, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_26, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_27, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_28, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_29, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_30, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_31, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_00, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_01, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_02, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_03, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_04, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_05, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_06, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_07, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_08, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_09, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_10, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_11, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_12, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_13, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_14, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_15, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_16, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_17, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_18, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of2_19, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QObject.connect(self.of1_00, QtCore.SIGNAL("toggled(bool)"), OutFlagCalc.calc)
        QtCore.QMetaObject.connectSlotsByName(OutFlagCalc)
        OutFlagCalc.setTabOrder(self.of1_00, self.of1_01)
        OutFlagCalc.setTabOrder(self.of1_01, self.of1_02)
        OutFlagCalc.setTabOrder(self.of1_02, self.of1_03)
        OutFlagCalc.setTabOrder(self.of1_03, self.of1_04)
        OutFlagCalc.setTabOrder(self.of1_04, self.of1_05)
        OutFlagCalc.setTabOrder(self.of1_05, self.of1_06)
        OutFlagCalc.setTabOrder(self.of1_06, self.of1_07)
        OutFlagCalc.setTabOrder(self.of1_07, self.of1_08)
        OutFlagCalc.setTabOrder(self.of1_08, self.of1_09)
        OutFlagCalc.setTabOrder(self.of1_09, self.of1_10)
        OutFlagCalc.setTabOrder(self.of1_10, self.of1_11)
        OutFlagCalc.setTabOrder(self.of1_11, self.of1_12)
        OutFlagCalc.setTabOrder(self.of1_12, self.of1_13)
        OutFlagCalc.setTabOrder(self.of1_13, self.of1_14)
        OutFlagCalc.setTabOrder(self.of1_14, self.of1_15)
        OutFlagCalc.setTabOrder(self.of1_15, self.of1_16)
        OutFlagCalc.setTabOrder(self.of1_16, self.of1_17)
        OutFlagCalc.setTabOrder(self.of1_17, self.of1_18)
        OutFlagCalc.setTabOrder(self.of1_18, self.of1_19)
        OutFlagCalc.setTabOrder(self.of1_19, self.of1_20)
        OutFlagCalc.setTabOrder(self.of1_20, self.of1_21)
        OutFlagCalc.setTabOrder(self.of1_21, self.of1_22)
        OutFlagCalc.setTabOrder(self.of1_22, self.of1_23)
        OutFlagCalc.setTabOrder(self.of1_23, self.of1_24)
        OutFlagCalc.setTabOrder(self.of1_24, self.of1_25)
        OutFlagCalc.setTabOrder(self.of1_25, self.of1_26)
        OutFlagCalc.setTabOrder(self.of1_26, self.of1_27)
        OutFlagCalc.setTabOrder(self.of1_27, self.of1_28)
        OutFlagCalc.setTabOrder(self.of1_28, self.of1_29)
        OutFlagCalc.setTabOrder(self.of1_29, self.of1_30)
        OutFlagCalc.setTabOrder(self.of1_30, self.of1_31)
        OutFlagCalc.setTabOrder(self.of1_31, self.of2_00)
        OutFlagCalc.setTabOrder(self.of2_00, self.of2_01)
        OutFlagCalc.setTabOrder(self.of2_01, self.of2_02)
        OutFlagCalc.setTabOrder(self.of2_02, self.of2_03)
        OutFlagCalc.setTabOrder(self.of2_03, self.of2_04)
        OutFlagCalc.setTabOrder(self.of2_04, self.of2_05)
        OutFlagCalc.setTabOrder(self.of2_05, self.of2_06)
        OutFlagCalc.setTabOrder(self.of2_06, self.of2_07)
        OutFlagCalc.setTabOrder(self.of2_07, self.of2_08)
        OutFlagCalc.setTabOrder(self.of2_08, self.of2_09)
        OutFlagCalc.setTabOrder(self.of2_09, self.of2_10)
        OutFlagCalc.setTabOrder(self.of2_10, self.of2_11)
        OutFlagCalc.setTabOrder(self.of2_11, self.of2_12)
        OutFlagCalc.setTabOrder(self.of2_12, self.of2_13)
        OutFlagCalc.setTabOrder(self.of2_13, self.of2_14)
        OutFlagCalc.setTabOrder(self.of2_14, self.of2_15)
        OutFlagCalc.setTabOrder(self.of2_15, self.of2_16)
        OutFlagCalc.setTabOrder(self.of2_16, self.of2_17)
        OutFlagCalc.setTabOrder(self.of2_17, self.of2_18)
        OutFlagCalc.setTabOrder(self.of2_18, self.of2_19)

    def retranslateUi(self, OutFlagCalc):
        OutFlagCalc.setWindowTitle(QtGui.QApplication.translate("OutFlagCalc", "OutFlagCalc", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_00.setText(QtGui.QApplication.translate("OutFlagCalc", "KEEP_RESOURCE_OPEN", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_01.setText(QtGui.QApplication.translate("OutFlagCalc", "WIDE_TIME_INPUT", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_02.setText(QtGui.QApplication.translate("OutFlagCalc", "NON_PARAM_VARY", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_03.setText(QtGui.QApplication.translate("OutFlagCalc", "RESERVED6", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_04.setText(QtGui.QApplication.translate("OutFlagCalc", "SEQUENCE_DATA_NEEDS_FLATTENING", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_05.setText(QtGui.QApplication.translate("OutFlagCalc", "I_DO_DIALOG", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_06.setText(QtGui.QApplication.translate("OutFlagCalc", "USE_OUTPUT_EXTENT", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_07.setText(QtGui.QApplication.translate("OutFlagCalc", "SEND_DO_DIALOG", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_08.setText(QtGui.QApplication.translate("OutFlagCalc", "DISPLAY_ERROR_MESSAGE", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_09.setText(QtGui.QApplication.translate("OutFlagCalc", "I_EXPAND_BUFFER", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_10.setText(QtGui.QApplication.translate("OutFlagCalc", "PIX_INDEPENDENT", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_11.setText(QtGui.QApplication.translate("OutFlagCalc", "I_WRITE_INPUT_BUFFER", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_12.setText(QtGui.QApplication.translate("OutFlagCalc", "I_SHRINK_BUFFER", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_13.setText(QtGui.QApplication.translate("OutFlagCalc", "WORKS_IN_PLACE", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_14.setText(QtGui.QApplication.translate("OutFlagCalc", "RESERVED8", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_15.setText(QtGui.QApplication.translate("OutFlagCalc", "CUSTOM_UI", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_16.setText(QtGui.QApplication.translate("OutFlagCalc", "RESERVED7", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_17.setText(QtGui.QApplication.translate("OutFlagCalc", "REFRESH_UI", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_18.setText(QtGui.QApplication.translate("OutFlagCalc", "NOP_RENDER", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_19.setText(QtGui.QApplication.translate("OutFlagCalc", "I_USE_SHUTTER_ANGLE", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_20.setText(QtGui.QApplication.translate("OutFlagCalc", "I_USE_AUDIO", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_21.setText(QtGui.QApplication.translate("OutFlagCalc", "I_AM_OBSOLETE", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_22.setText(QtGui.QApplication.translate("OutFlagCalc", "FORCE_RERENDER", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_23.setText(QtGui.QApplication.translate("OutFlagCalc", "PiPL_OVERRIDES_OUTDATA_OUTFLAGS", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_24.setText(QtGui.QApplication.translate("OutFlagCalc", "I_HAVE_EXTERNAL_DEPENDENCIES", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_25.setText(QtGui.QApplication.translate("OutFlagCalc", "DEEP_COLOR_AWARE", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_26.setText(QtGui.QApplication.translate("OutFlagCalc", "SEND_UPDATE_PARAMS_UI", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_27.setText(QtGui.QApplication.translate("OutFlagCalc", "AUDIO_FLOAT_ONLY", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_28.setText(QtGui.QApplication.translate("OutFlagCalc", "AUDIO_IIR", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_29.setText(QtGui.QApplication.translate("OutFlagCalc", "I_SYNTHESIZE_AUDIO", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_30.setText(QtGui.QApplication.translate("OutFlagCalc", "AUDIO_EFFECT_TOO", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_31.setText(QtGui.QApplication.translate("OutFlagCalc", "AUDIO_EFFECT_ONLY", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_00.setText(QtGui.QApplication.translate("OutFlagCalc", "SUPPORTS_QUERY_DYNAMIC_FLAGS", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_01.setText(QtGui.QApplication.translate("OutFlagCalc", "I_USE_3D_CAMERA", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_02.setText(QtGui.QApplication.translate("OutFlagCalc", "I_USE_3D_LIGHTS", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_03.setText(QtGui.QApplication.translate("OutFlagCalc", "PARAM_GROUP_START_COLLAPSED_FLAG", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_04.setText(QtGui.QApplication.translate("OutFlagCalc", "I_AM_THREADSAFE", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_05.setText(QtGui.QApplication.translate("OutFlagCalc", "CAN_COMBINE_WITH_DESTINATION", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_06.setText(QtGui.QApplication.translate("OutFlagCalc", "DOESNT_NEED_EMPTY_PIXELS", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_07.setText(QtGui.QApplication.translate("OutFlagCalc", "REVEALS_ZERO_ALPHA", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_08.setText(QtGui.QApplication.translate("OutFlagCalc", "PRESERVES_FULLY_OPAQUE_PIXELS", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_09.setText(QtGui.QApplication.translate("OutFlagCalc", "SUPPORTS_SMART_RENDER", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_10.setText(QtGui.QApplication.translate("OutFlagCalc", "RESERVED9", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_11.setText(QtGui.QApplication.translate("OutFlagCalc", "FLOAT_COLOR_AWARE", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_12.setText(QtGui.QApplication.translate("OutFlagCalc", "I_USE_COLORSPACE_ENUMERATION", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_13.setText(QtGui.QApplication.translate("OutFlagCalc", "I_AM_DEPRECATED", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_14.setText(QtGui.QApplication.translate("OutFlagCalc", "PPRO_DO_NOT_CLONE_SEQUENCE_DATA_FOR_RENDER", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_15.setText(QtGui.QApplication.translate("OutFlagCalc", "RESERVED10", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_16.setText(QtGui.QApplication.translate("OutFlagCalc", "AUTOMATIC_WIDE_TIME_INPUT", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_17.setText(QtGui.QApplication.translate("OutFlagCalc", "I_USE_TIMECODE", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_18.setText(QtGui.QApplication.translate("OutFlagCalc", "DEPENDS_ON_UNREFERENCED_MASKS", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_19.setText(QtGui.QApplication.translate("OutFlagCalc", "OUTPUT_IS_WATERMARKED", None, QtGui.QApplication.UnicodeUTF8))
        self.PF_OutFlags.setText(QtGui.QApplication.translate("OutFlagCalc", "PF_OutFlags", None, QtGui.QApplication.UnicodeUTF8))
        self.PF_OutFlags2.setText(QtGui.QApplication.translate("OutFlagCalc", "PF_OutFlag2", None, QtGui.QApplication.UnicodeUTF8))
        self.PF_OutFlags_value.setText(QtGui.QApplication.translate("OutFlagCalc", "AE_Effect_Global_OutFlags", None, QtGui.QApplication.UnicodeUTF8))
        self.PF_OutFlags2_value.setText(QtGui.QApplication.translate("OutFlagCalc", "AE_Effect_Global_OutFlags_2", None, QtGui.QApplication.UnicodeUTF8))
        self.PF_GlobalCmd.setText(QtGui.QApplication.translate("OutFlagCalc", "PF_GlobalCmd code", None, QtGui.QApplication.UnicodeUTF8))
        self.of1_result.setText(QtGui.QApplication.translate("OutFlagCalc", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.of2_result.setText(QtGui.QApplication.translate("OutFlagCalc", "0", None, QtGui.QApplication.UnicodeUTF8))

